services:
  filecodebox:
    image: lanol/filecodebox:latest
    volumes:
      - filecodebox-data:/app/data:rw
    restart: unless-stopped
    ports:
      - "12345:12345"
volumes:
  filecodebox-data: